name: Deployment - Reusable Workflow

on:
    workflow_call: 
      inputs:
        kubectl-version:
            description: Provide the required Kubectl version
            default: v1.26.0
            required: false
            type: string
        k8s-manifest-dir:
            description: Directory containing Kubernetes manifests files
            default: kubernetes/
            required: true
            type: string 
        deploy-environment:
            description: Provide the Deployment Environment
            default: development
            required: true
            type: string
      outputs:
        application-url:
           value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL  }} 
      secrets:
        k8s-kubeconfig:
          required: true
        mongodb-password:
          required: true
        aws-access-key:
          required: true
        aws-secret-key:
          required: true
        


jobs:
    reuse-deploy:
        environment: 
            name: ${{ inputs.deploy-environment }}
            url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        outputs:
            APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            
            - name: Install kubectl CLI
              uses: azure/setup-kubectl@v3
              with:
                version: '${{ inputs.kubectl-version }}'

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.aws-access-key }}
                aws-secret-access-key: ${{ secrets.aws-secret-key }}
                aws-region: ${{vars.AWS_REGION}}  # Replace with your region if different

            - name: Set Kubeconfig file
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.k8s-kubeconfig }}


            - name: Verify kubectl version and get nodes
              run: |
                kubectl version
                echo ---------------------------------------------------
                kubectl get nodes
                
            
            - name: Save Nginx Ingress Controller IP as a GITHUB Environment Variable
              run: |
                echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")" >> $GITHUB_ENV
            
            - name: Replace Token in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '_{_'
                tokenSuffix: '_}_'
                files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS }}
                IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
                INGRESS_IP:  ${{ env.INGRESS_IP }}

            - name: Check files
              run: |
                cat ${{ inputs.k8s-manifest-dir }}*.yaml

            - name: Create MongoDB Secret
              run: |
               kubectl apply -f ${{ inputs.k8s-manifest-dir }}/secrets.yml
              
            - name: Deploy to Dev Env
              run: |
                kubectl apply -f ${{ inputs.k8s-manifest-dir }}

            - name: Set App Ingress Host URL
              id: set-ingress-host-address
              run: |
                echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> "$GITHUB_OUTPUT"